version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Group all dependencies into a single pull request
    groups:
      all-dependencies:
        patterns:
          - '*'
    # Use pnpm constraints
    versioning-strategy: 'increase'
    # Set the commit message
    commit-message:
      prefix: 'chore'
      include: 'scope'
    # Assign specific reviewers
    reviewers:
      - 'CODEOWNERS'
    # Limit the number of PRs
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    groups:
      all-actions:
        patterns:
          - '*'
